### ISSUE TITLE
An option to make mxshift relative to the initial_tfm position

### ISSUE THREAD

**Issue by ianshmean** [HolyLab/RegisterQD.jl#22]
I believe it's the case that the `mxshift` limit is applied +/- the center of the image. It would be great to have the option to define `mxshift` relative to the `initial_tfm` position, which would be helpful for registering relative to the first frame in a stack, and using the previous `tform` to constrain/speed up analysis. i.e. `mxshift` would then be entered as the maximum expected frame-frame shift, but `fixed` would remain as frame 1.

Currently if the image sequence is drifting away from the first fixed image, the logical `mxshift` value has to grow, and can become much larger than the expected frame-frame shift given it is enforced symmetrically about the middle of the image.

I could try to propose a PR, but it seems the current approach might be quite baked in.
Perhaps there's a simple trick to get the desired functionality?

**Comment by Cody-G** [comment]
Thanks for your contributions to RegisterQD! As I recall 'mxshift' and other limit parameters are already applied after the initial transform. Taking rigid registration as an example you can see that the initial transform is applied within the function being optimized by QuadDIRECT, so the search space is centered on the initial transform rather than the identity transform: https://github.com/HolyLab/RegisterQD.jl/blob/master/src/rigid.jl#L81

If that's unclear or if we're handling this inconsistently in other places just let me know.

**Comment by timholy** [comment]
Thanks for your reply @Cody-G!

To further expand on his answer, we take the image coordinates literally. If you use `OffsetArrays` to put the origin in a particular place, all the coordinate transformation magic will use it as the origin. `centered` is a convenient way of generating an `OffsetArray` where the origin is approximately at the center (within a pixel), but it's not obligatory.

**Comment by ianshmean** [comment]
Great news. I'm glad I was mistaken and apologies for the confusion.

It might be nice to adjust the docstrings to something like: 
```
optimizes a simple shift (translation) to minimize the mismatch between `fixed` 
and `moving` using the QuadDIRECT algorithm with the constraint that no 
shifts larger than `mxshift` (after an optional `initial_tfm`) will be considered
```

**Comment by timholy** [comment]
Works for me!
